export const mockBookings = [
    {
      id: "BK1001",
      guestName: "John Smith",
      propertyName: "Grand Hotel Resort",
      checkInDate: "2023-06-15",
      checkOutDate: "2023-06-20",
      status: "confirmed",
      totalPrice: 1250.0,
    },
    {
      id: "BK1002",
      guestName: "Sarah Johnson",
      propertyName: "Seaside Villa",
      checkInDate: "2023-07-01",
      checkOutDate: "2023-07-07",
      status: "pending",
      totalPrice: 1800.0,
    },
    {
      id: "BK1003",
      guestName: "Michael Brown",
      propertyName: "Mountain Lodge",
      checkInDate: "2023-06-25",
      checkOutDate: "2023-06-28",
      status: "confirmed",
      totalPrice: 750.0,
    },
    {
      id: "BK1004",
      guestName: "Emily Davis",
      propertyName: "City Center Hotel",
      checkInDate: "2023-07-10",
      checkOutDate: "2023-07-12",
      status: "cancelled",
      totalPrice: 450.0,
    },
    {
      id: "BK1005",
      guestName: "Robert Wilson",
      propertyName: "Luxury Resort & Spa",
      checkInDate: "2023-08-05",
      checkOutDate: "2023-08-12",
      status: "confirmed",
      totalPrice: 2800.0,
    },
    {
      id: "BK1006",
      guestName: "Jennifer Lee",
      propertyName: "Beachfront Bungalow",
      checkInDate: "2023-07-20",
      checkOutDate: "2023-07-25",
      status: "pending",
      totalPrice: 1350.0,
    },
    {
      id: "BK1007",
      guestName: "David Miller",
      propertyName: "Historic Downtown Inn",
      checkInDate: "2023-06-18",
      checkOutDate: "2023-06-21",
      status: "confirmed",
      totalPrice: 675.0,
    },
    {
      id: "BK1008",
      guestName: "Lisa Anderson",
      propertyName: "Lakeside Retreat",
      checkInDate: "2023-08-15",
      checkOutDate: "2023-08-20",
      status: "pending",
      totalPrice: 1200.0,
    },
  ]
  
  export const mockProperties = [
    "Grand Hotel Resort",
    "Seaside Villa",
    "Mountain Lodge",
    "City Center Hotel",
    "Luxury Resort & Spa",
    "Beachfront Bungalow",
    "Historic Downtown Inn",
    "Lakeside Retreat",
    "Urban Boutique Hotel",
    "Country Cottage",
  ]
  
  export const mockGuests = [
    "John Smith",
    "Sarah Johnson",
    "Michael Brown",
    "Emily Davis",
    "Robert Wilson",
    "Jennifer Lee",
    "David Miller",
    "Lisa Anderson",
    "James Taylor",
    "Patricia Moore",
    "Richard Martin",
    "Elizabeth White",
  ]
  